"""Sisera canonical domain financial types.

Implements ADR-002: monetary balances, quantities, prices, and fees are represented with
`decimal.Decimal` (fixed-point) rather than binary floating point. Binary float may be
used only for informational analytics (indicators, charting), and is converted to a
canonical representation at any domain or ledger boundary.

These value objects are the shared vocabulary the rest of Sisera operates on — exchange-
specific objects must never leak past the connector boundary (ADR-005).
"""

from sisera_domain.agent import (
    Agent,
    AgentCapital,
    AutonomyLevel,
    InvalidLifecycleTransition,
    LifecycleStage,
    StrategyManifest,
    validate_lifecycle_transition,
)
from sisera_domain.approval import (
    Approval,
    ApprovalEngine,
    ApprovalPolicy,
    ApprovalRequest,
    ApprovalRule,
)
from sisera_domain.auth import (
    AccessPolicy,
    Desk,
    Membership,
    Organization,
    Permission,
    Role,
    User,
)
from sisera_domain.circuit import CircuitBreaker, EmergencyMode, KillScope, KillSwitch
from sisera_domain.decision import Decision, DecisionKind, DecisionLedger, SignalComponent
from sisera_domain.differential import (
    DifferentialEngine,
    FactorDirection,
    FactorReading,
    MarketDiff,
    MarketFactor,
)
from sisera_domain.execution import PaperExecutionEngine, PaperFill, VenueAdapter, VenueCapabilities
from sisera_domain.governance import (
    DriftMonitor,
    DriftReport,
    ModelRegistry,
    ModelStatus,
    ModelVersion,
    PromotionDenied,
)
from sisera_domain.instrument import (
    CanonicalAsset,
    FundingModel,
    Instrument,
    InstrumentStatus,
    InstrumentType,
    MarginModel,
    OptionType,
    SymbolResolver,
    VenueInstrument,
)
from sisera_domain.intent import (
    IntentAction,
    InvalidIntent,
    TradeIntent,
    TradeTrigger,
    TriggerType,
    compile_intent,
)
from sisera_domain.ledger import EntryType, Ledger, LedgerEntry, Posting
from sisera_domain.money import (
    Asset,
    Money,
    Percentage,
    Price,
    Quantity,
    quantize_to_step,
    round_quantity_to_lot,
)
from sisera_domain.notifications import (
    Category,
    Channel,
    InMemoryNotifier,
    LogNotifier,
    Notification,
    NotificationService,
    Notifier,
    Severity,
)
from sisera_domain.oms import OrderManager
from sisera_domain.order import (
    InvalidStateTransition,
    Order,
    OrderSide,
    OrderState,
    OrderStateMachine,
    OrderType,
    TimeInForce,
)
from sisera_domain.portfolio import Portfolio, Position
from sisera_domain.prediction import (
    MarketKind,
    MarketStatus,
    PredictionEvent,
    PredictionMarket,
    PredictionOutcome,
    PredictionPosition,
    PredictionSettlement,
    ResolutionOracle,
    ResolutionRule,
    settle_position,
)
from sisera_domain.reconcile import Discrepancy, DiscrepancySeverity, Reconciler
from sisera_domain.risk import RiskCheckResult, RiskEngine, RiskPolicy, RiskReason
from sisera_domain.routing import (
    CostBreakdown,
    RouteConstraints,
    RouteLeg,
    RoutePlan,
    SmartOrderRouter,
    VenueHealth,
    VenueQuote,
)
from sisera_domain.stress import Scenario, StressEngine, StressImpact
from sisera_domain.tca import FillRecord, FillTCA, TCAEngine

__all__ = [
    "Asset",
    "Money",
    "Percentage",
    "Price",
    "Quantity",
    "quantize_to_step",
    "round_quantity_to_lot",
    "CanonicalAsset",
    "FundingModel",
    "Instrument",
    "InstrumentStatus",
    "InstrumentType",
    "MarginModel",
    "OptionType",
    "SymbolResolver",
    "VenueInstrument",
    "EntryType",
    "Ledger",
    "LedgerEntry",
    "Posting",
    "Order",
    "OrderSide",
    "OrderState",
    "OrderStateMachine",
    "OrderType",
    "TimeInForce",
    "InvalidStateTransition",
    "OrderManager",
    "PaperExecutionEngine",
    "PaperFill",
    "VenueAdapter",
    "VenueCapabilities",
    "Portfolio",
    "Position",
    "RiskCheckResult",
    "RiskEngine",
    "RiskPolicy",
    "RiskReason",
    "CostBreakdown",
    "RouteConstraints",
    "RouteLeg",
    "RoutePlan",
    "SmartOrderRouter",
    "VenueHealth",
    "VenueQuote",
    "FillRecord",
    "FillTCA",
    "TCAEngine",
    "Scenario",
    "StressEngine",
    "StressImpact",
    "MarketKind",
    "MarketStatus",
    "PredictionEvent",
    "PredictionMarket",
    "PredictionOutcome",
    "PredictionPosition",
    "PredictionSettlement",
    "ResolutionOracle",
    "ResolutionRule",
    "settle_position",
    "Agent",
    "AgentCapital",
    "AutonomyLevel",
    "InvalidLifecycleTransition",
    "LifecycleStage",
    "StrategyManifest",
    "validate_lifecycle_transition",
    "Decision",
    "DecisionKind",
    "DecisionLedger",
    "SignalComponent",
    "Approval",
    "ApprovalEngine",
    "ApprovalPolicy",
    "ApprovalRequest",
    "ApprovalRule",
    "CircuitBreaker",
    "EmergencyMode",
    "KillScope",
    "KillSwitch",
    "Discrepancy",
    "DiscrepancySeverity",
    "Reconciler",
    "IntentAction",
    "InvalidIntent",
    "TradeIntent",
    "TradeTrigger",
    "TriggerType",
    "compile_intent",
    "AccessPolicy",
    "Desk",
    "Membership",
    "Organization",
    "Permission",
    "Role",
    "User",
    "Category",
    "Channel",
    "InMemoryNotifier",
    "LogNotifier",
    "Notification",
    "NotificationService",
    "Notifier",
    "Severity",
    "DriftMonitor",
    "DriftReport",
    "ModelRegistry",
    "ModelStatus",
    "ModelVersion",
    "PromotionDenied",
    "DifferentialEngine",
    "FactorDirection",
    "FactorReading",
    "MarketDiff",
    "MarketFactor",
]
